### ISSUE TITLE
Unary operations are not implemented

### ISSUE THREAD

**Issue by jarkonik** [jarkonik/rocklang#17]

**Comment by oczekrb** [comment]
What kind of unary operators should be implemented? I was in code that there is only minus unary operator implemented in the parser. 
Instead of `+` and `-` unary operators we want some more like `!` or address `&` and indirection `*`?

**Comment by jarkonik** [comment]
General handling of unary needs to be implemented within the compiler, but i guess for now we only have minus operator to handle there

**Comment by oczekrb** [comment]
Ok, so in scope of this issue i will implement the minus unary operator in compilator layer.
